### ISSUE TITLE
overzealous toml table formatting?

### ISSUE THREAD

**Issue by Gankra** [bholley/cargo-vet#103]
If you `cargo vet fmt` tests/test-project it will do this transform:

```toml
[[audits.clap]]
notes = "test for custom criteria (low-grade and high-grade)"
criteria = "safe-to-deploy"
version = "3.1.8"
dependency-criteria = { atty = ["safe-to-run"], bitflags = ["audited", "fuzzed"] }
```

```toml
[[audits.clap]]
notes = "test for custom criteria (low-grade and high-grade)"
criteria = "safe-to-deploy"
version = "3.1.8"

[audits.clap.dependency-criteria]
atty = ["safe-to-run"]
bitflags = ["audited", "fuzzed"]
```

Which seems hellish/unreadable/dangerous?
